version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
test:
  adapter: postgresql
  database: test
  pool: 5
  host: localhost
  username: postgres
  password: null
production:
  adapter: postgresql
  database: test
  pool: 5
  host: localhost
  username: postgres
  password: null
blocks: []
